# Generated by Django 4.1 on 2022-08-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelcar',
            table='model_cars',
        ),
    ]
