# Generated by Django 4.1 on 2022-08-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
        ('car', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cars',
            field=models.ManyToManyField(blank=True, to='car.car'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owners',
            field=models.ManyToManyField(blank=True, to='owner.owner'),
        ),
    ]
