# Generated by Django 4.1 on 2022-08-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_cars_alter_store_owners'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='store',
            table='stores',
        ),
    ]
