version: "3.3"

services:
  app_pgdb:
    image: postgres
    container_name: app_pgdata
    env_file:
      - .env
    volumes:
      - app_pgdata:/data/postgres
    network_mode: host
    environment: # Set up postgres database name and password
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - app_pgdb
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    network_mode: host
    environment: # Set up postgres database name and password
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

volumes:
  app_pgdata:
    driver: local
