# Generated by Django 4.1 on 2022-08-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color', '0002_color_created_at_color_updated_at'),
        ('model_car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='color.color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model_car.modelcar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
