# Generated by Django 4.1 on 2022-08-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sale',
            table='sales',
        ),
    ]
